### ISSUE TITLE
Cal.com: retrieve the cancel/rescheduling URL from the API and return it as a data point

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#150]
# The problem

Cal.com allows for canceling or rescheduling of already made appointments. They do that by sending a confirmation email of the appointment, and in that email, there's a link to reschedule/cancel the appointment. However, we have a customer (Better Health) who would like to take control over the notifications sent to their patients and therefore would like to disable all communication that Cal.com sends (like the confirmation email).

> It would be neat I suppose if we could grab the cancel/reschedule links for use within our Email/SMS templates, which would allow us to move away from Cal.com notifications altogether, which would make for a more uniform experience.

# What it needs

Return the reschedule/cancel URL of the appointment as a `string` data point which in itself is a fairly trivial effort. But there's some discovery needed to see whether this is actually possible.

## Discovery

It's currently not clear whether Cal.com returns the rescheduling/cancel URL via their API and if not, whether there is another way we can (manually) compose that URL based on other parameters. Eg: if the cancel URL is always `https://cal.com/cancel/{bookingId}` then we can easily compose it by using the `bookingId`. So this part needs tech discovery.

If the discovery yields the result that we cannot retrieve or compose the cancel URL ourselves, then obviously we cannot solve the problem at hand for now.

## Boundaries

It should be the "Get booking" action that returns the URL, not the "Book appointment" action.

**Comment by michal-grzelak** [comment]
@nckhell I checked the API and there is no direct URL in the returned object. However, it can be constructed not with `bookingId`, but in the data there is `uid` field and the URLs look as follows. Given the data:
```json
{
    "booking": {
        "id": 429174,
        "userId": 70544,
        "description": "",
        "eventTypeId": 242678,
        "uid": "jtYWJ9bSqdtwwo9vtveuUy",
        "title": "15 Min Meeting between Michał Grzelak and Test",
        "startTime": "2023-06-02T10:15:00.000Z",
        "endTime": "2023-06-02T10:30:00.000Z",
        "attendees": [
            {
                "email": "test@test.com",
                "name": "Test",
                "timeZone": "Europe/Warsaw",
                "locale": "en"
            }
        ],
        "user": {
            "email": "michal.grzelak@htdevelopers.com",
            "name": "Michał Grzelak",
            "timeZone": "Europe/Warsaw",
            "locale": null
        },
        "payment": [],
        "metadata": {
            "videoCallUrl": "https://app.cal.com/video/jtYWJ9bSqdtwwo9vtveuUy",
            "awellPathwayId": "c7YSkmcmfKrU",
            "awellActivityId": "EXTmqcCbxcGICtwNFp-0p"
        },
        "status": "ACCEPTED",
        "responses": {
            "email": "test@test.com",
            "name": "Test",
            "location": {
                "optionValue": "",
                "value": "integrations:daily"
            }
        }
    }
}
```
- CANCEL - https://app.cal.com/booking/jtYWJ9bSqdtwwo9vtveuUy?cancel=true
- RESCHEDULE - https://app.cal.com/reschedule/jtYWJ9bSqdtwwo9vtveuUy

So you can see that `uid` field is used to construct those URLs.
