### ISSUE TITLE
Twilio: Send message using a Messaging Service SID

### ISSUE THREAD

**Issue by bejoinka** [awell-health/awell-extensions#157]
//EDIT NICK: see scope in my comment 👇 

My understanding from [this link](https://www.twilio.com/docs/messaging/services/services-send-messages#sending-messages-with-a-messaging-service) is that Twilio supports sending messages from a phone number _or_ from a `messagingServiceSid` (and potentially `ALSO` a phone number, which must be assigned to that messaging service id)

Twilio posted information about 10DLC [here](https://support.twilio.com/hc/en-us/articles/1260800720410-What-is-A2P-10DLC-), so it's going to require some understanding of requirements from @nckhell before we convert into a todo for engineers.

we either need to create a new action that supports the messaging service SID, or we need to add an optional field in our current action. Needs further discovery

**Comment by bejoinka** [comment]
still unclear whether or not this should be a new action or an additional (optional) field on the current action.

**Comment by nckhell** [comment]
# Need

Being able to send an SMS with Twilio from a Messaging Service (specified by a `messagingServiceSid`) whereas today you can only send an SMS by specifying a from number.

# Functional scope

## Settings

* Make `fromNumber` optional whereas today it's required and change the description to "A Twilio phone number that you own in E.164 format which will be used to send text messages. If you are using a Messaging Service you can leave this field empty."
* Add a new settings field `messagingServiceSid` which is also optional and has the following description "The SID of the Messaging Service you want to associate with the Message. If you are not using a Messaging Service but a "from" number, then you can leave this field empty."

## Changes to the current "Send SMS" action

* Change the label of the action to "Send SMS (with from number)"
* Change the description of the action to "Send a text message from a given telephone number to a recipient of your choice."
* Add a new action field `fromNumber` which should come first in the list, is optional, and has the following description: "The phone number that will be used to send the message. If left blank, the from number specified in the settings will be used."
* Throw a human-readable error when `fromNumber` in settings AND in action field are not specified (with `onError` function)

## Add a new action

* Action label: "Send SMS (with Messaging Service)"
* The description of the action to "Send a text message from a specified from number to a recipient of your choice."
* Has the following action fields and descriptions
  * `messagingServiceSid` (string): "The SID of the Messaging Service you want to associate with the Message. If left blank, the SID specified in the settings will be used."
  * `recipient`: see already existing action
  * `message`: see already existing action
* Throw a human-readable error when `messagingServiceSid` in settings AND in action field are not specified (with `onError` function)

## Readme

Update the README (new action) and the Changelog.

**Comment by bejoinka** [comment]
FYI, this extension needs to be live, tested, and in production before quarter-end
