### ISSUE TITLE
Healthie - Evaluate API responses to assess the success of mutations

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#158]
We have custom actions in our Healthie extension that perform a mutation in Healthie (create a resource, edit/update a resource, or delete a resource). Currently, we assess the success of those mutations based on the HTTP status code we receive in the response. I.e. if it’s a 200, we consider the mutation successful (eg: the task has been created) - if not, then we consider that the action failed and we call the `onError` function.

However, Healthie is a GraphQL API and as many GraphQL APIs do they can return a 200 OK response even when there’s an error with the mutation.

> 200 OK
> This status code indicates that the request was successful and that the server is returning data. However, a GraphQL API can also return a 200 OK in cases where the request contains an error, such as an invalid object name or field, or when a record is not found.

# Example: task creation

The Healthie API returns an HTTP 200 status code but the task was actually not created because the user associated with the API key doesn’t have permission to do so. Because we receive a 200 status, we do call the `onComplete` function, and the action is incorrectly marked as successfully completed.

![image](https://github.com/awell-health/awell-extensions/assets/5594064/109bd329-9d7d-4ab9-9731-4853d532257b)

What the user sees (success while it's not):

<img width="448" alt="Screenshot 2023-06-07 at 12 30 16" src="https://github.com/awell-health/awell-extensions/assets/5594064/d5316a37-0500-4ba6-a82c-8a94975533be">

# To do

Go over all actions in Healthie that interact with the Healthie API through a mutation (creating, updating, or deleting a resource) and assess how and if we can check that action was really successful (eg: was the task really deleted? the patient really created?).

# Functional requirements

Try to capture the error message from the Healthie API and return it with the `onError` function so the reason of failure is also communicated to the end user. Eg: in the example above `You do not have permission to create this task`.

**Comment by michal-grzelak** [comment]
@nckhell It seems that what can be done in all healthie actions is to include this snippet (alter properties of course):
```ts
// completeTask.ts
if (!isNil(data.updateTask?.messages)) {
    const errors = mapHealthieToActivityError(data.updateTask?.messages)
    await onError({
      events: errors,
    })
    return
}
```
I did it in some actions, can do after `DocuSign`.

**Comment by nckhell** [comment]
@michal-grzelak Looks good, I added one functional requirement but I think that's covered with the code snippet you shared. So feel free to move this issue forward.
