### ISSUE TITLE
Healthie - Allow setting a date reminder interval when interval type is "once"

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#161]
# Problem

> Also see https://github.com/awell-health/awell-extensions/issues/47 where we originally implemented reminders.

When we added the ability to configure reminders with the "Create task" action a couple of new action fields were added like:
* `reminderIntervalType` (string)
* `reminderIntervalValue` (string)

`reminderIntervalValue` is an action field of value type `string` but the problem is that depending on the value of the`reminderIntervalType` action field it should either be a string or a date.

> When `reminderIntervalType` type is set to "daily", leave `reminderIntervalValue` blank. For "weekly" interval, send in comma separated all lower-case days of the week (e.g wednesday, friday). **For "once", send in the date in ISO8601 format (e.g 2020-11-28)**.

So when `reminderIntervalType` equals "weekly", then `reminderIntervalValue` should be a comma-separated string of all lower-case days of the week. If it equals `once`, then `reminderIntervalValue` should be a date.

# Limitations

There are a couple of limitations we have to work with:
1. Action fields can only have one type (i.e. `reminderIntervalValue` cannot be a string and a date at the same time)
2. We cannot conditionally show or hide an action field based on the value of another action field

# Discovery

I would propose the following change but suggestions are welcome as well:
* `reminderIntervalType` (string) - stays as is to prevent breaking changes
* `reminderIntervalValue` (string) - stays as is to prevent breaking changes
* add a new optional action field called `reminderIntervalValueOnce` which has a value type of `date`

Set the following descriptions for the action fields:
* `reminderIntervalValue`: When the interval type is set to "daily" or "once", leave this field blank. For "weekly" interval, send in comma separated all lower-case days of the week (e.g wednesday, friday).
* `reminderIntervalValueOnce`: When the interval type is set to "daily" or "weekly", leave this field blank. For "once" interval, set or select a date.

Make sure that technically we grab the right value to send to the API. If `reminderIntervalValue` equals `weekly`, then use the value of `reminderIntervalValue` (this should also be the default to avoid breaking changes). If `reminderIntervalValue` equals `once`, then use the value of `reminderIntervalValueOnce`.

**Comment by bejoinka** [comment]
FYI, this extension needs to be live, tested, and in production before quarter-end
