### ISSUE TITLE
Sendgrid Extension

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#162]
# Need

We have a customer that uses Sendgrid and we therefore want to have a Sendgrid extension.

# Context

* We did some work in the past already on a Sendgrid extension but it was discarded back then. However, the PR might be useful to get you going quickly: https://github.com/awell-health/awell-extensions/pull/19
* This MR should not be merged until Nick is back OR after @ebomcke-awell or @bejoinka acknowledged that it can be merged. Reason: we already have a Sendgrid **plugin** in our system (legacy) and we probably have to check if there are no conflicts with the extension that we are building or think about how to deprecate the legacy plugin. Anyway, development & reviewing can happen.

**Why create the extension now?**
Wellinks needs an additional action for Sendgrid and we don't want to build that into the legacy plugin anymore. So seems like the right thing to do is to create the extension now and add the additional actions immediately.

# Functional scope

## The basics

I am gonna keep this short as I believe there are sufficient references of extensions that integrate with other email providers (see Mailgun and Mailchimp extension) and Sendgrid has good documentation.

**But, what's minimally needed:**
1. A new extension: "Sendgrid"
2. Extensions settings, probably similar to Mailgun/Mailchimp extension
3. Minimally two actions with similar action fields as Mailgun/Mailchimp:
  * Send email (to, subject, body)
  * Send email with template (to, template, subject, template variables)
4. Create a README and Changelog
5. Basic validation of settings and action fields

## Additional "Add or update contact" action

> See https://docs.sendgrid.com/api-reference/contacts/add-or-update-a-contact

**Functional requirements:**
* The action will add or update only one contact (even tho the API endpoint allows an array of contacts)
* Has the following action fields
  * List IDs (optional, a comma-separated string of list IDs the contact will be added to)
  * Email (string, email, required)
  * Custom fields (JSON, optional)
* You don't have to take into account that it's an async API endpoint. If the API returns a `202` status code then you can mark the action as completed. 

Please make sure that relevant information from the Sendgrid docs make it into the README. Eg: `Please note that custom fields need to have been already created if you wish to set their values for the contacts being upserted. To do this, please use the "Create Custom Field Definition" endpoint.` AND `The contact to update will be determined only by the email field and any fields omitted from the request will remain as they were. A contact's ID cannot be used to update the contact.`.

**Comment by bejoinka** [comment]
FYI, this extension needs to be live, tested, and in production before quarter-end
