### ISSUE TITLE
[EXT-12] Error boilerplate in actions needs improvement

### ISSUE THREAD

**Issue by bejoinka** [awell-health/awell-extensions#180]
There's a bunch of `if err instanceof ZodError`, `if err instanceof AxiosError`, and catch-all error boilerplate all over the place.

Let's remove it and push those handlers to the `awell-extension-server`, and clean up some of these actions.

This activity will need to be completed after [this issue from awell-extension-server](https://github.com/awell-health/awell-extension-server/issues/30). Please refer to the Should Have / Could Have in that referenced issue.

<sub>[EXT-12](https://linear.app/awell/issue/EXT-12/error-boilerplate-in-actions-is-annoying)</sub>

**Comment by rahulkeerthi** [comment]
Test comment

**Comment by rahulkeerthi** [comment]
Testing
