### ISSUE TITLE
[EXT-4] [Sendbird] Create user action: make `nickname` optional and set a sensible default

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#219]
`nickname` is currently a required action field (because it's required for making the API call to Sendbird) but we want to make it optional and set a sensible default.
- `nickname` becomes optional
- If the action field has a value of undefined or empty string, set the `nickname` to `{patientFirstName} {patientLastName}` (both available in `payload.patient`.
- If both the `firstName` and the `lastName` of the patient are not known in Awell and `nickname` action field is not specified either, then we should throw an error. I.e. we should never allow calling the Sendbird API when `nickname` has no value
- Change the description of the action field to `The user's nickname. Maximum length is 80 characters. If left empty, we will use the patient's first and last name.`

<sub>[EXT-4](https://linear.app/awell/issue/EXT-4/sendbird-create-user-action-make-nickname-optional-and-set-a-sensible)</sub>

**Comment by rahulkeerthi** [comment]
@nickgeraceelization can you help @mateusz.kubiak with a sendbird account please?

**Comment by rahulkeerthi** [comment]
@mateusz.kubiak i've invited you to the account, you can pick this up when you're ready

**Comment by rahulkeerthi** [comment]
Re-reviewed, the logic is still incorrect — please see the comment I left
