### ISSUE TITLE
[EXT-20] [Elation] rename onCreatePatient webhook to patientCreatedOrUpdated

### ISSUE THREAD

**Issue by michal-grzelak** [awell-health/awell-extensions#222]
Currently Elation's `onCreatePatient` is run on every `saved/deleted/signed off` event, the actual event action is not checked. This webhook should check if `saved` is invoked. See [https://docs.elationhealth.com/reference/the-event-object](https://docs.elationhealth.com/reference/the-event-object) for more details.

Unfortunately there is no separate `created` event in Elation's webhooks, so it means this webhook will still run on `UPDATE`. This is Elation's limitation as of right now, so it means this webhook should probably be renamed, so that users won't get confused.

What to do:

* check if action equals `saved` for `onCreatePatient` webhook

<sub>From [SyncLinear.com](https://synclinear.com) | [EXT-20](https://linear.app/awell/issue/EXT-20/[elation]-webhooks-enhancement)</sub>

**Comment by michal-grzelak** [comment]
@rahulkeerthi Question in here: Elation supports 3 events (2 for patients webhook `saved/deleted`, see [https://docs.elationhealth.com/reference/the-event-object](https://docs.elationhealth.com/reference/the-event-object)). It means that even if we narrow the webhook check to `saved` event, it means that this webhook will trigger on both Create and Update of the patient. Should the webhook name also be changed? It's potentially a breaking change

**Comment by rahulkeerthi** [comment]
I will have a think about this, but for now, leave it with me 🙏

**Comment by rahulkeerthi** [comment]
@michal.grzelak let's rename the webhook to `patientCreatedOrUpdated` — does that make sense?
