### ISSUE TITLE
[EXT-7] New Extension: Canvas Medical

### ISSUE THREAD

**Issue by bejoinka** [awell-health/awell-extensions#84]
# Canvas Medical

Canvas Medical is another EHR. It is one of our goals to have five EHR integrations this quarter, and Canvas will be number 3!

## What are the benefits of a Canvas integration?

Canvas' FHIR API adheres to the FHIR R4 specification ([read more here](https://docs.canvasmedical.com/reference/getting-started-with-your-api)). FHIR is becoming industry-standard so capturing these resources and mapping them to Awell will be useful beyond just Canvas' integration.

They have a nice postman collection, ready to be forked. Should make testing the API fairly simple. They also have an SDK. Again, seems like it has the opportunity to be pretty straightforward.

## What endpoints should we support?

Original scope from [V1C-52](https://linear.app/awell/issue/V1C-52/canvas-medical-v1):

* [Create a patient](https://docs.canvasmedical.com/reference/patient-create)
* [Update a patient](https://docs.canvasmedical.com/reference/patient-update)
* [Create an appointment](https://docs.canvasmedical.com/reference/appointment-create)
* [Update an appointment](https://docs.canvasmedical.com/reference/appointment-update)
* [Create a task](https://docs.canvasmedical.com/reference/task-create)
* [Create Questionnaire Response](https://docs.canvasmedical.com/reference/questionnaireresponse-create)
* [Read questionnaire responses](https://docs.canvasmedical.com/reference/questionnaireresponse-read)

v1 Beta Scope:

* [X] Patient create
* [X] Patient update
* [X] Task create
* [X] Task update
* [X] Appointment create
* [X] Appointment update
* [X] Create questionnaire responses

## Additional notes

* Let's avoid deprecated fields and values
* Any already completed actions not in the list above should, for now, not be removed but just not exported from the index in the extension folder
* Do not use JSON data points as inputs or outputs in new actions as this is not supported by the platform yet. JSON as extension action field type is 👍
* Done but excluded (i.e. will not be exported from actions index) due to lack of support for objects and arrays
  * [X] Patient read
  * [X] Appointment read
  * [X] Task read
  * [X] Read questionnaire responses

<sub>From [SyncLinear.com](https://synclinear.com) | [EXT-7](https://linear.app/awell/issue/EXT-7/new-extension-canvas-medical)</sub>

**Comment by rahulkeerthi** [comment]
@michal.grzelak @mateusz.kubiak I spoke to danijel and I think I know what needs to be done to get the extensions running locally. I will work with you both on Tuesday to get awell-next up and running + running the extensions server with local extensions code so you can test your extensions work locally.

**Comment by rahulkeerthi** [comment]
We've decided on a different approach that means you don't need to run awell-next locally next week (yet! that will come soon!) 

You can merge minor version of extensions code and this will deploy to our staging environment automatically. I will give you access to staging and show you how it works on Monday.

**Comment by rahulkeerthi** [comment]
Instructions are in the README: [https://github.com/awell-health/awell-extension-server#readme](https://github.com/awell-health/awell-extension-server#readme)

**Comment by rahulkeerthi** [comment]
Because they require merging support for JSON data type work that we aren’t 100% happy with

**Comment by rahulkeerthi** [comment]
Yes, of course! @mateusz.kubiak can you ensure you cherry pick that excess code into another branch so we don’t lose it?

**Comment by rahulkeerthi** [comment]
@mateusz.kubiak for now we shouldn't have any actions that use `FieldType.JSON` — these [should not be exported from the index of the extension](https://linear.app/awell/issue/EXT-7#comment-2d71cb85). Happy to chat about this for a bit if you need more clarity

**Comment by rahulkeerthi** [comment]
Yes, sorry you are right — JSON as input field type is 👍, JSON *data points* as input + outputs is 🚫

**Comment by rahulkeerthi** [comment]
@michal.grzelak are you able to do a first review now? I’ll review this after lunchtime anyway

**Comment by rahulkeerthi** [comment]
Demo to be created on Monday by @mateusz.kubiak

**Comment by rahulkeerthi** [comment]
The following actions have been released 

![image.png](https://uploads.linear.app/d9f0efd7-88a3-4e86-a589-247b95a95ca0/3a690c9f-966e-4e2b-a32a-b7b6c0704e7c/99aecd18-8289-40f1-90c1-c75df3c829a3)

Demos:

[https://htdhealth.slack.com/files/U016FKYJ6AH/F05QX5GDX1A/create-questionnaire-response.mov](https://htdhealth.slack.com/files/U016FKYJ6AH/F05QX5GDX1A/create-questionnaire-response.mov)

[https://htdhealth.slack.com/files/U016FKYJ6AH/F05QX5HDFLL/create-update-appointment.mov](https://htdhealth.slack.com/files/U016FKYJ6AH/F05QX5HDFLL/create-update-appointment.mov)

[https://htdhealth.slack.com/files/U016FKYJ6AH/F05R7B407NV/create-update-patient.mov](https://htdhealth.slack.com/files/U016FKYJ6AH/F05R7B407NV/create-update-patient.mov)

[https://htdhealth.slack.com/files/U016FKYJ6AH/F05QNMHLT7G/creating-updating-tasks.mov](https://htdhealth.slack.com/files/U016FKYJ6AH/F05QNMHLT7G/creating-updating-tasks.mov)
