### ISSUE TITLE
Healthie - Get patient action: Return dob as a date data point instead of a string

### ISSUE THREAD

**Issue by nckhell** [awell-health/awell-extensions#90]
# Context

<img width="975" alt="Screenshot 2023-04-18 at 13 56 55" src="https://user-images.githubusercontent.com/5594064/232769917-9181be6f-4bc0-4e44-9362-0c53a313a2b3.png">

https://awellhealth.atlassian.net/wiki/spaces/AWELL/pages/3492773961/Have+5+different+Extensions+implemented+in+a+live+care+flow?focusedCommentId=3493822565#Additional-field-mapping-problems

# Situation today

The "Get patient" action ingests new data points in a care flow, one of those is the `dob` data point which is typed as a string.

```typescript
const dataPoints = {
  ...,
  dob: {
    key: 'dob',
    valueType: 'string',
  },
} satisfies Record<string, DataPointDefinition>
```

# To be situation

```typescript
const dataPoints = {
  ...,
  dob: {
    key: 'dob',
    valueType: 'date', // should be ISO8601 date string
  },
} satisfies Record<string, DataPointDefinition>
```

Store the dob string we receive from Healthie in a date data point. We might need to try and parse the incoming string value from Healthie to a data and then use `date-fns` to parse it to ISO8601 string date.

Pseudocode
```javascript
import { isValid, formatISO } from 'date-fns'

const getDateValue = (incoming_dob: string) => {
  const date = new Date(incoming_dob)
  const isValidDate = isValid(date)

  if (isValidDate) return formatISO(date)

  return undefined
}
```

**Comment by bejoinka** [comment]
sounds like this should be high prio, because it's a breaking change and if it's not used in production yet then we want to do it before it is.

**Comment by nckhell** [comment]
@bejoinka In order to not make it a breaking change, we could actually follow Etienne's suggestion [here](https://github.com/awell-health/awell-extensions/issues/81#issuecomment-1511437971) which kinda relates to the same thing.

So you would end up with:

```typescript
const dataPoints = {
  ...,
  dob: {
    key: 'dob',
    valueType: 'string', // keep this as string, backward compatible
  },
  validatedDob: {
    key: 'dob',
    valueType: 'date', // this can be a date and we know a valid date will be stored here
  },
} satisfies Record<string, DataPointDefinition>
```

**Comment by bejoinka** [comment]
sure. but oh man, can you look ahead and see the tech debt we might be accruing vis-a-vis datapoints in custom actions?

Customer: "what's the difference between the `validated_phone_number` field and the `phones` field and the `validated_phones` field?

maybe a brief discussion that includes etienne here. i'm thinking specifically w/r/t objects and arrays, which are two more types we don't yet support.

**Comment by nckhell** [comment]
Yeah, from a UX perspective that's definitely the worst thing we could do. I agree.
